# num_packets: 1000
input_pcap: "traces/Anonymized_bras_dataset/BRAS_capture_network-transmission_1.pcap"
output_pcap: "generated_int.pcap"

truncate_64B: false

int_udp_dst_port: 5000

original_proto: 6  # TCP
base_src_ip: "10.0.0.1"
base_dst_ip: "10.0.0.18"
src_port: 12345
dst_port: 80
num_flows: 15

rhc: 5
hops: [1, 2, 3, 4, 5]

instruction_bits: [0, 2, 3, 7]  # Node ID, Hop latency

payload: "hello world!"
